# "Global" variables.
# Keep this file for reference.

git_repo: https://github.com/publicscience/argos.git
venv_path: /var/env/argos
app_path: /var/www/argos
app_name: argos
remote_user: ubuntu
region: us-east-1
base_ami: ami-7d317314
db_user: argos_user
db_pass: password

# Whatever key you specify here should
# be added to `keys/`,
# e.g. `keys/<key_name>.pem`.
key_name: argos_dummy


aes_key: '123456789abcdefg123456789abcdefg' # must be 32 bytes
aes_iv: '123456789abcdefg' # must be 16 bytes
secret_key: 'some-secret-key'

s3_bucket_name: foo
aws_access_key_id: your_access_key_id
aws_secret_access_key: your_secret_access_key

email_host: smtp.gmail.com
email_port: 587
error_email_user: someone@gmail.com
error_email_password: somepass
error_admins: ['someone@gmail.com']

celery_email_user: someone@gmail.com
celery_email_password: somepass
celery_admin_name: some admin
celery_admin_email: admin@mail.com

bizvizz_api_key: foo
opensecrets_api_key: foo
instagram_client_id: foo
sunlight_api_key: foo
flickr_client_id: foo
