# "Global" variables.
# Keep this file for reference.

git_repo: https://github.com/publicscience/argos.git
venv_path: /var/env/argos
app_path: /var/www/argos
app_name: argos
remote_user: ubuntu
region: us-east-1
base_ami: ami-7d317314
db_user: argos_user
db_pass: password

# Whatever key you specify here should
# be added to `keys/`,
# e.g. `keys/<key_name>.pem`.
key_name: argos_dummy

admin_name: some admin
admin_email: admin@mail.com

aes_key: '123456789abcdefg123456789abcdefg' # must be 32 bytes
aes_iv: '123456789abcdefg' # must be 16 bytes
secret_key: 'some-secret-key'

s3_bucket_name: foo
