jena_url: http://mirrors.gigenet.com/apache//jena/binaries/apache-jena-2.11.1.tar.gz
fuseki_url: http://mirrors.gigenet.com/apache//jena/binaries/jena-fuseki-1.0.1-distribution.tar.gz
ner_url: http://nlp.stanford.edu/software/stanford-ner-2013-06-20.zip
knowledge_path: /srv/knowledge/
knowledge_db: /srv/knowledge/knodb
