- hosts: 'tag_Name_{{ app_name }}-{{ env_name }}-worker'
  sudo: yes
  remote_user: '{{ remote_user }}'
  vars:
      db_host: '{{ hostvars[groups.tag_Name_{{ app_name }}-{{ env_name }}-database[0]].ec2_private_dns_name }}'
      knowledge_host: '{{ hostvars[groups.tag_Name_{{ app_name }}-{{ env_name }}-knowledge[0]].ec2_private_dns_name }}'
      broker_host: '{{ hostvars[groups.tag_Name_{{ app_name }}-{{ env_name }}-broker[0]].ec2_private_dns_name }}'
  roles:
      - common
      - app
      - worker
